---
- hosts: localhost
  connection: local
  remote_user: ansible
  become: true
  tasks:
    - name: deploy nginx docker container
      docker_container:
        image: piyushsolanki/nginxp:latest
        name: nginx
        state: started
        auto_remove: true
        ports:
          - "80:80"
