---
- hosts: localhost
  connection: local
  remote_user: ansible
  become: true
  
  tasks:
  - name: deploy nginx docker container
    command: docker build -t  piyushsolanki/nginxp:latest .

  - name: create container using simple-devops-image
    command: docker run -d --name nginx -p 80:80 piyushsolanki/nginxp:latest
